### ISSUE TITLE
Include in Third-Party Providers list

### ISSUE THREAD

**Issue by adamjimenez** [chrishemmings/oauth2-digitalocean#1]
This is great. Should it be listed on:
https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/thirdparty.md

**Comment by chrishemmings** [comment]
Hey there,

Thanks for the interest,  I have created a PR for this change,

https://github.com/thephpleague/oauth2-client/pull/588

**Comment by chrishemmings** [comment]
The PR has been accepted and the provider is now on the list. 👍
